name: NuGet Push

on: 
  push:
    tags:
    - '*'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup
        uses: actions/setup-dotnet@v1

      - name: Install tool
        run: dotnet tool install -g dotnetCampus.TagToVersion

      - name: Set tag to version
        run: dotnet TagToVersion -t ${{ github.ref }}  
        
      - name: Pack
        run: dotnet build --configuration Release
      - name: Push
        run: dotnet nuget push .\bin\Release\*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NugetKey }} --skip-duplicate --no-symbols 1
